### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by philipbl** [y-board/y-board#14]
@jgoeders, I ran `cppcheck` on the code and it found a couple of errors in `yaudio.cpp`:

https://github.com/y-board/y-board-v3/blob/25532eeb8bf02d753e835d5a06528f3b32f70db5/src/yaudio.cpp#L236-L244

`err` is not initialized but used on line 244.

https://github.com/y-board/y-board-v3/blob/25532eeb8bf02d753e835d5a06528f3b32f70db5/src/yaudio.cpp#L433-L437

Line 434 doesn't do anything, right?

**Comment by jgoeders** [comment]
Fixed in #15
