### ISSUE TITLE
Allow note volume changes

### ISSUE THREAD

**Issue by philipbl** [y-board/y-board#17]
I can't remember if we talked about this, but it would be nice to change the volume of the notes. There is variable for it:

https://github.com/y-board/y-board-v3/blob/4ea0cbf84cf3b1be0c76656e4e17a632f508599f/src/yaudio.cpp#L54

I'm happy submit a PR to create an accessor, but I wanted to check that changing the variable won't cause other problems.

**Comment by jgoeders** [comment]
It is controlled through an option in the string. This ensures it is changed at the correct time, otherwise notes will become queued up at the current volume.

**Comment by philipbl** [comment]
That's right. I haven't looked at your mini language to see all of the features it has. Thanks!
