### ISSUE TITLE
Update `play_sound` API

### ISSUE THREAD

**Issue by philipbl** [y-board/y-board#4]
There is a couple of things we could do with the play_sound API.

1. Add optional audio callback API for when playback is finished. I was thinking something like `play_sound(filename, callback)`. The callback would get called when the sound was done playing.

2. Add ability to block until it the sound is done playing. Something like `play_sound_blocking(filename)` or `play_sound(filename, blocking)`

**Comment by jgoeders** [comment]
Blocking and non-blocking audio functions have been added in #10
