### ISSUE TITLE
Add WiFi support

### ISSUE THREAD

**Issue by philipbl** [y-board/y-board#7]
Allow people to connect to WiFi and send data?

**Comment by philipbl** [comment]
@jgoeders, I would like to get your thoughts on this. I am leaning toward not adding it to the library. I'm thinking that the library should only include code that interfaces with the _hardware_. My concern is that if we add WiFi support, then do we need to add HTTP support? WiFi itself is kind of useless without something that uses it. Networking support is so specific on the needs of the user that it will be hard to generalize it into a nice interface. We can add a demo that shows how to use WiFi, but it won't be anything different from all the tutorials online that show how to connect to WiFi. What do you think?

**Comment by jgoeders** [comment]
I agree - it sounds like if we do anything, it belongs more in the demos.
